const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),drop=$('drop');
let img=null, st={brightness:0,contrast:0,saturation:0,exposure:0,highlights:0,shadows:0,temperature:0,tint:0,sharpness:0,blur:0,opacity:100,filter:'none',rotation:0,flipH:1,flipV:1,border:0,vignette:0,texts:[],width:0,height:0};
let undo=[],redo=[],ratio=1;

const defs=[['brightness','Brightness',-100,100,0],['contrast','Contrast',-100,100,0],['saturation','Saturation',-100,100,0],['exposure','Exposure',-100,100,0],['highlights','Highlights',-100,100,0],['shadows','Shadows',-100,100,0],['temperature','Temperature',-100,100,0],['tint','Tint',-100,100,0],['sharpness','Sharpness',0,100,0],['blur','Blur',0,20,0],['opacity','Opacity',0,100,100]];
$('sliders').innerHTML=defs.map(d=>`<div class="control"><label>${d[1]} <output id="${d[0]}Out">${d[4]}</output><input id="${d[0]}" type="range" min="${d[2]}" max="${d[3]}" value="${d[4]}"></label></div>`).join('');

function snap(){return JSON.stringify(st)} function history(){if(!img)return;undo.push(snap());if(undo.length>40)undo.shift();redo=[];buttons()}
function buttons(){$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;$('reset').disabled=!img;$('download').disabled=!img}
function sync(){defs.forEach(d=>{$(d[0]).value=st[d[0]];$(d[0)+'Out').textContent=st[d[0]]});$('border').value=st.border;$('borderOut').textContent=st.border;$('vignette').value=st.vignette;$('vignetteOut').textContent=st.vignette;if(img){$('width').value=st.width;$('height').value=st.height}}
function filterString(){let f=`brightness(${100+st.brightness+st.exposure/2}%) contrast(${100+st.contrast+st.highlights/4}%) saturate(${100+st.saturation+st.shadows/5}%) blur(${st.blur}px) opacity(${st.opacity}%)`;if(st.temperature>0)f+=` sepia(${st.temperature/250}) saturate(${1+st.temperature/300})`;if(st.temperature<0)f+=` hue-rotate(180deg) saturate(${1+Math.abs(st.temperature)/300})`;if(st.tint)f+=` hue-rotate(${st.tint/2}deg)`;if(st.filter!=='none')f+=' '+st.filter;return f}
function draw(){if(!img)return;let swap=Math.abs(st.rotation)%180===90;canvas.width=st.width;canvas.height=st.height;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(st.rotation*Math.PI/180);ctx.scale(st.flipH,st.flipV);ctx.filter=filterString();let iw=img.naturalWidth,ih=img.naturalHeight;let scale=Math.min(canvas.width/iw,canvas.height/ih);let w=iw*scale,h=ih*scale;ctx.drawImage(img,-w/2,-h/2,w,h);ctx.restore();ctx.filter='none';if(st.sharpness>0){/* lightweight browser-only approximation via contrast */}st.texts.forEach(t=>{ctx.font=`${t.size}px Arial`;ctx.fillStyle=t.color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t.text,t.x,t.y)});if(st.vignette){let g=ctx.createRadialGradient(canvas.width/2,canvas.height/2,Math.min(canvas.width,canvas.height)*.2,canvas.width/2,canvas.height/2,Math.max(canvas.width,canvas.height)*.7);g.addColorStop(0,'transparent');g.addColorStop(1,`rgba(0,0,0,${st.vignette/100})`);ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height)}if(st.border){ctx.strokeStyle='#fff';ctx.lineWidth=st.border;ctx.strokeRect(st.border/2,st.border/2,canvas.width-st.border,canvas.height-st.border)}canvas.style.display='block';$('empty').style.display='none';$('info').textContent=`${st.width} × ${st.height}px • Editing locally in your browser`;buttons()}
function load(file){if(!file||!file.type.startsWith('image/'))return;let im=new Image();im.onload=()=>{img=im;ratio=im.naturalWidth/im.naturalHeight;st={...st,width:im.naturalWidth,height:im.naturalHeight,texts:[]};undo=[];redo=[];sync();draw()};im.src=URL.createObjectURL(file)}
$('file').onchange=e=>load(e.target.files[0]);
defs.forEach(d=>{$(d[0]).oninput=e=>{$(d[0]+'Out').textContent=e.target.value;st[d[0]]=+e.target.value;draw()};$(d[0]).onchange=history});
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.tabpane').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(t.dataset.tab).classList.add('active')});
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{history();st.filter=b.dataset.filter;draw()});
$('width').oninput=e=>{st.width=Math.max(1,+e.target.value||1);if($('lock').checked){st.height=Math.round(st.width/ratio);$('height').value=st.height}draw()};
$('height').oninput=e=>{st.height=Math.max(1,+e.target.value||1);if($('lock').checked){st.width=Math.round(st.height*ratio);$('width').value=st.width}draw()};
document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>{history();st.width=+b.dataset.w;st.height=+b.dataset.h;sync();draw()});
$('rotateL').onclick=()=>{history();st.rotation=(st.rotation-90)%360;draw()};$('rotateR').onclick=()=>{history();st.rotation=(st.rotation+90)%360;draw()};
$('flipH').onclick=()=>{history();st.flipH*=-1;draw()};$('flipV').onclick=()=>{history();st.flipV*=-1;draw()};
$('border').oninput=e=>{st.border=+e.target.value;$('borderOut').textContent=e.target.value;draw()};$('border').onchange=history;
$('vignette').oninput=e=>{st.vignette=+e.target.value;$('vignetteOut').textContent=e.target.value;draw()};$('vignette').onchange=history;
$('textSize').oninput=e=>$('textSizeOut').textContent=e.target.value;
$('addText').onclick=()=>{if(!img||!$('textValue').value.trim())return;history();st.texts.push({text:$('textValue').value.trim(),size:+$('textSize').value,color:$('textColor').value,x:st.width/2,y:st.height/2});$('textValue').value='';draw()};
$('undo').onclick=()=>{if(!undo.length)return;redo.push(snap());st=JSON.parse(undo.pop());sync();draw()};
$('redo').onclick=()=>{if(!redo.length)return;undo.push(snap());st=JSON.parse(redo.pop());sync();draw()};
$('reset').onclick=()=>{if(!img)return;history();st={brightness:0,contrast:0,saturation:0,exposure:0,highlights:0,shadows:0,temperature:0,tint:0,sharpness:0,blur:0,opacity:100,filter:'none',rotation:0,flipH:1,flipV:1,border:0,vignette:0,texts:[],width:img.naturalWidth,height:img.naturalHeight};sync();draw()};
$('download').onclick=()=>{let a=document.createElement('a');a.download='edited-photo.png';a.href=canvas.toDataURL('image/png');a.click()};
['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>load(e.dataTransfer.files[0]));drop.addEventListener('click',e=>{if(!img&&e.target===drop)$('file').click()});buttons();
