(()=>{"use strict";
const $=id=>document.getElementById(id);
const S={pages:[],current:-1,tool:"select",history:[],future:[],pdfQuality:.78,camera:null,facing:"environment"};
S.zoom=1;S.pdfZoom=1;S.pdfPreviewPage=1;S.pdfDoc=null;
function setZoom(v){S.zoom=Math.max(.35,Math.min(2.5,v));$("zoomLabel").textContent=Math.round(S.zoom*100)+"%";canvas.style.width=(canvas.width*S.zoom)+"px";canvas.style.height=(canvas.height*S.zoom)+"px";overlay.style.width=(canvas.width*S.zoom)+"px";overlay.style.height=(canvas.height*S.zoom)+"px"}
function fitZoom(){const area=document.querySelector(".canvas-area");const p=current();if(!p?.img)return;const maxW=area.clientWidth-70,maxH=area.clientHeight-70;S.zoom=Math.min(maxW/canvas.width,maxH/canvas.height,1);if(S.zoom<.35)S.zoom=.35;$("zoomLabel").textContent=Math.round(S.zoom*100)+"%";canvas.style.width=(canvas.width*S.zoom)+"px";canvas.style.height=(canvas.height*S.zoom)+"px";overlay.style.width=(canvas.width*S.zoom)+"px";overlay.style.height=(canvas.height*S.zoom)+"px"}
function renderPdfPreviewFromCurrent(){const body=$("pdfViewerBody");const p=current();if(!p?.img){body.innerHTML='<div class="viewer-empty">Import a PDF or document to see a live preview here.</div>';return}body.innerHTML="";const c=document.createElement("canvas");const max=1300,s=Math.min(1,max/Math.max(p.img.naturalWidth,p.img.naturalHeight));c.width=Math.round(p.img.naturalWidth*s);c.height=Math.round(p.img.naturalHeight*s);c.getContext("2d").drawImage(p.img,0,0,c.width,c.height);c.style.width=(c.width*S.pdfZoom)+"px";c.style.height=(c.height*S.pdfZoom)+"px";body.appendChild(c);$("pdfPageInfo").textContent=`Page ${S.current+1} of ${S.pages.length}`}
function updatePdfZoom(v){S.pdfZoom=Math.max(.5,Math.min(2.5,v));$("pdfZoomLabel").textContent=Math.round(S.pdfZoom*100)+"%";renderPdfPreviewFromCurrent()}

const canvas=$("pageCanvas"),ctx=canvas.getContext("2d",{alpha:false}),overlay=$("overlay"),octx=overlay.getContext("2d");
const toast=m=>{const t=$("toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2300)};
const current=()=>S.pages[S.current];
const snapshot=()=>JSON.stringify(S.pages.map(p=>({src:p.src,rotation:p.rotation,filter:p.filter,brightness:p.brightness,contrast:p.contrast,crop:p.crop,marks:p.marks,texts:p.texts})));
function commit(){S.history.push(snapshot());if(S.history.length>30)S.history.shift();S.future=[];buttons()}
function buttons(){$("undoBtn").disabled=!S.history.length;$("redoBtn").disabled=!S.future.length}
function restore(s){const arr=JSON.parse(s);S.pages=arr.map(p=>({...p,img:null}));let left=S.pages.length;if(!left){S.current=-1;refresh();return}S.pages.forEach(p=>{const im=new Image();im.onload=()=>{p.img=im;if(!--left){S.current=Math.min(S.current,S.pages.length-1);refresh()}};im.src=p.src})}
$("undoBtn").onclick=()=>{if(!S.history.length)return;S.future.push(snapshot());restore(S.history.pop());buttons()};
$("redoBtn").onclick=()=>{if(!S.future.length)return;S.history.push(snapshot());restore(S.future.pop());buttons()};

function makePage(src,img){return{src,img,rotation:0,filter:"none",brightness:0,contrast:0,crop:[],marks:[],texts:[]}}
function fileToImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),im=new Image();im.onload=async()=>{try{await im.decode()}catch{}resolve(makePage(url,im))};im.onerror=reject;im.src=url})}
async function importFiles(files){for(const f of files){try{if(f.type==="application/pdf"||/\.pdf$/i.test(f.name))await importPdf(f);else if(f.type.startsWith("image/"))S.pages.push(await fileToImage(f));else toast("Unsupported: "+f.name)}catch(e){console.error(e);toast("Could not open "+f.name)}}if(S.pages.length){S.current=S.pages.length-1;refresh();toast("Imported successfully")}}
function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement("script");s.src=src;s.onload=res;s.onerror=()=>rej(new Error(src));document.head.appendChild(s)})}
async function pdfjs(){if(window.pdfjsLib)return window.pdfjsLib;await loadScript("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js");window.pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";return window.pdfjsLib}
async function pdflib(){if(window.PDFLib)return window.PDFLib;await loadScript("https://cdnjs.cloudflare.com/ajax/libs/pdf-lib/1.17.1/pdf-lib.min.js");return window.PDFLib}
async function importPdf(file){toast("Opening PDF…");const lib=await pdfjs(),pdf=await lib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;const add=[];for(let n=1;n<=pdf.numPages;n++){const pg=await pdf.getPage(n),base=pg.getViewport({scale:1}),scale=Math.min(2,1600/base.width),vp=pg.getViewport({scale}),c=document.createElement("canvas");c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);const x=c.getContext("2d",{alpha:false});x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);await pg.render({canvasContext:x,viewport:vp,background:"white"}).promise;const b=await new Promise(r=>c.toBlob(r,"image/jpeg",.9));add.push(await fileToImage(new File([b],file.name+"-"+n+".jpg",{type:"image/jpeg"})));pg.cleanup?.()}S.pages.push(...add);toast(`${pdf.numPages} PDF page${pdf.numPages===1?"":"s"} loaded`)}

function filter(p){let f=`brightness(${1+p.brightness/100}) contrast(${1+p.contrast/100})`;if(p.filter==="gray")f+=" grayscale(1)";if(p.filter==="document")f+=" grayscale(1) contrast(1.35) brightness(1.05)";if(p.filter==="sepia")f+=" sepia(1)";if(p.filter==="vivid")f+=" saturate(1.35)";return f}
function render(){const p=current();if(!p?.img)return;const iw=p.img.naturalWidth,ih=p.img.naturalHeight,rot=p.rotation%180!==0,w=rot?ih:iw,h=rot?iw:ih;canvas.width=w;canvas.height=h;overlay.width=w;overlay.height=h;ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.rotate(p.rotation*Math.PI/180);ctx.drawImage(p.img,-iw/2,-ih/2,iw,ih);ctx.restore();if(p.filter!=="none"||p.brightness||p.contrast){const t=document.createElement("canvas");t.width=w;t.height=h;const x=t.getContext("2d");x.filter=filter(p);x.drawImage(canvas,0,0);ctx.drawImage(t,0,0)}octx.clearRect(0,0,w,h);p.marks.forEach(m=>{octx.strokeStyle=m.color;octx.lineWidth=m.width;octx.lineCap="round";octx.beginPath();m.path.forEach((q,i)=>i?octx.lineTo(q.x,q.y):octx.moveTo(q.x,q.y));octx.stroke()});p.texts.forEach(t=>{octx.fillStyle=t.color;octx.font=`${t.size}px Arial`;octx.fillText(t.text,t.x,t.y)});if(S.tool==="crop"&&p.crop.length){octx.strokeStyle="#65e8ff";octx.lineWidth=Math.max(4,w/300);octx.beginPath();p.crop.forEach((q,i)=>i?octx.lineTo(q.x,q.y):octx.moveTo(q.x,q.y));if(p.crop.length===4)octx.closePath();octx.stroke();p.crop.forEach(q=>{octx.fillStyle="#65e8ff";octx.beginPath();octx.arc(q.x,q.y,9,0,Math.PI*2);octx.fill()})}}
function thumb(p,size=280){const c=document.createElement("canvas"),s=Math.min(1,size/Math.max(p.img.naturalWidth,p.img.naturalHeight));c.width=Math.max(1,p.img.naturalWidth*s);c.height=Math.max(1,p.img.naturalHeight*s);c.getContext("2d").drawImage(p.img,0,0,c.width,c.height);return c.toDataURL("image/jpeg",.72)}
function refresh(){const has=S.pages.length>0;$("emptyState").classList.toggle("hidden",has);$("stageWrap").classList.toggle("hidden",!has);$("bottomToolbar").classList.toggle("hidden",!has);$("exportBtn").disabled=!has;$("ocrBtn").disabled=!has;$("compressImageBtn").disabled=!has;$("compressPdfBtn").disabled=!has;$("docTitle").value=has?`Document • ${S.pages.length} page${S.pages.length===1?"":"s"}`:"Untitled document";$("thumbs").innerHTML="";S.pages.forEach((p,i)=>{const d=document.createElement("div");d.className="thumb "+(i===S.current?"active":"");d.innerHTML=`<img src="${thumb(p)}"><small>Page ${i+1}</small>`;d.onclick=()=>{S.current=i;refresh();buildToolbar()};$("thumbs").appendChild(d)});$("pageGrid").innerHTML="";S.pages.forEach((p,i)=>{const d=document.createElement("div");d.className="page-card";d.draggable=true;d.dataset.i=i;d.innerHTML=`<img src="${thumb(p,420)}"><div class="page-meta"><span>Page ${i+1}</span><button class="button mini" data-delete="${i}">Delete</button></div>`;d.onclick=e=>{if(e.target.dataset.delete!=null)return;S.current=i;go("scan")};d.ondragstart=e=>e.dataTransfer.setData("text/plain",i);d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();const from=+e.dataTransfer.getData("text/plain"),to=i;if(from===to)return;commit();const [x]=S.pages.splice(from,1);S.pages.splice(to,0,x);S.current=to;refresh()};$("pageGrid").appendChild(d)});document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{commit();S.pages.splice(+b.dataset.delete,1);S.current=Math.min(S.current,S.pages.length-1);refresh()});if(has){render();buildToolbar();setZoom(S.zoom);renderPdfPreviewFromCurrent()}buttons()}
function go(v){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(`${v}View`).classList.add("active");document.querySelectorAll(".rail-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));if(v==="scan"&&S.pages.length)render()}
document.querySelectorAll(".rail-item[data-view]").forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));

function buildToolbar(){const p=current(),bar=$("bottomToolbar");if(!p)return;let h="";if(S.tool==="crop")h=`<button class="chip" data-act="clearCrop">Clear corners</button><button class="button primary" data-act="applyCrop">Apply perspective crop</button>`;else if(S.tool==="enhance")h=`<button class="chip" data-filter="none">Original</button><button class="chip" data-filter="document">Document</button><button class="chip" data-filter="gray">B&W</button><span class="slider">Brightness <input id="bright" type="range" min="-40" max="40" value="${p.brightness}"></span><span class="slider">Contrast <input id="contrast" type="range" min="-40" max="70" value="${p.contrast}"></span>`;else if(S.tool==="filters")h=["none","document","gray","sepia","vivid"].map(f=>`<button class="chip ${p.filter===f?"active":""}" data-filter="${f}">${f}</button>`).join("");else if(S.tool==="rotate")h=`<button class="chip" data-act="left">↶ 90°</button><button class="chip" data-act="right">↷ 90°</button><button class="chip" data-act="half">180°</button>`;else if(S.tool==="annotate"||S.tool==="signature")h=`<span class="slider">Color <input class="color" id="penColor" type="color" value="${S.tool==="signature"?"#1f4ed8":"#e53d58"}"></span><button class="chip" data-act="clearMarks">Clear</button><span class="slider">Draw directly on the page</span>`;else if(S.tool==="text")h=`<input id="textValue" placeholder="Text" style="background:#111a2a;border:1px solid #30405b;color:#fff;border-radius:8px;padding:8px"><button class="button primary" data-act="addText">Add text</button>`;else h=`<button class="chip" data-act="enhance">Auto enhance</button><button class="chip" data-act="right">Rotate</button><button class="chip" data-act="duplicate">Duplicate</button><button class="chip" data-act="delete">Delete page</button>`;bar.innerHTML=h;bar.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{commit();p.filter=b.dataset.filter;render();buildToolbar()});bar.querySelectorAll("[data-act]").forEach(b=>b.onclick=()=>act(b.dataset.act));$("bright")?.addEventListener("input",e=>{p.brightness=+e.target.value;render()});$("contrast")?.addEventListener("input",e=>{p.contrast=+e.target.value;render()})}
function act(a){const p=current();if(!p)return;if(a==="enhance"){commit();p.filter="document";p.brightness=6;p.contrast=18}if(a==="left"||a==="right"){commit();p.rotation=(p.rotation+(a==="left"?270:90))%360}if(a==="half"){commit();p.rotation=(p.rotation+180)%360}if(a==="duplicate"){commit();S.pages.splice(S.current+1,0,{...p,marks:[...p.marks],texts:[...p.texts]});S.current++}if(a==="delete"){commit();S.pages.splice(S.current,1);S.current=Math.min(S.current,S.pages.length-1)}if(a==="clearCrop"){p.crop=[]}if(a==="clearMarks"){commit();p.marks=[];p.texts=[]}if(a==="addText"){const t=$("textValue")?.value.trim();if(t){commit();p.texts.push({text:t,x:80,y:120,size:46,color:"#111827"})}}if(a==="applyCrop")applyPerspective();refresh()}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
overlay.addEventListener("pointerdown",e=>{const p=current();if(!p)return;if(S.tool==="crop"){if(p.crop.length<4)p.crop.push(point(e));render();return}if(S.tool==="annotate"||S.tool==="signature"){commit();p.marks.push({color:$("penColor")?.value||"#e53d58",width:Math.max(5,canvas.width/250),path:[point(e)]});overlay.setPointerCapture?.(e.pointerId)}});
overlay.addEventListener("pointermove",e=>{const p=current();if(!p||!(S.tool==="annotate"||S.tool==="signature")||!overlay.hasPointerCapture?.(e.pointerId))return;p.marks.at(-1).path.push(point(e));render()});overlay.addEventListener("pointerup",e=>overlay.releasePointerCapture?.(e.pointerId));
async function applyPerspective(){const p=current();if(p.crop.length!==4){toast("Select four corners first");return}const q=p.crop,sx=canvas.width,sy=canvas.height,minX=Math.max(0,Math.floor(Math.min(...q.map(a=>a.x)))),maxX=Math.min(sx,Math.ceil(Math.max(...q.map(a=>a.x)))),minY=Math.max(0,Math.floor(Math.min(...q.map(a=>a.y)))),maxY=Math.min(sy,Math.ceil(Math.max(...q.map(a=>a.y))));const c=document.createElement("canvas");c.width=maxX-minX;c.height=maxY-minY;c.getContext("2d").drawImage(canvas,minX,minY,c.width,c.height,0,0,c.width,c.height);const b=await new Promise(r=>c.toBlob(r,"image/jpeg",.94));commit();S.pages[S.current]=await fileToImage(new File([b],"cropped.jpg",{type:"image/jpeg"}));toast("Crop applied");refresh()}

async function pdfBytes(indices=S.pages.map((_,i)=>i),quality=S.pdfQuality){const PDF=await pdflib(),pdf=await PDF.PDFDocument.create(),old=S.current;for(const i of indices){S.current=i;render();const b=await new Promise(r=>canvas.toBlob(r,"image/jpeg",quality)),jpg=await pdf.embedJpg(new Uint8Array(await b.arrayBuffer())),page=pdf.addPage([595,842]),scale=Math.min(555/jpg.width,802/jpg.height);page.drawImage(jpg,{x:(595-jpg.width*scale)/2,y:(842-jpg.height*scale)/2,width:jpg.width*scale,height:jpg.height*scale})}S.current=old;return pdf.save()}
function download(data,name,type){const a=document.createElement("a"),u=URL.createObjectURL(new Blob([data],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
async function exportPdf(indices){if(!S.pages.length)return;toast("Building PDF…");download(await pdfBytes(indices),"DocScan-document.pdf","application/pdf");toast("PDF ready")}
$("exportBtn").onclick=()=>exportPdf();$("mergeBtn").onclick=()=>exportPdf();$("extractBtn").onclick=async()=>{const s=prompt("Page numbers, e.g. 1,3,4");if(!s)return;const ids=s.split(",").map(x=>+x.trim()-1).filter(x=>x>=0&&x<S.pages.length);if(ids.length)exportPdf(ids)};$("pdfQuality").onchange=e=>S.pdfQuality=+e.target.value;

async function ocrLoad(){if(window.Tesseract)return;await loadScript("https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js")}
$("ocrBtn").onclick=async()=>{if(!current())return;go("ocr");$("ocrStatus").textContent="Loading OCR…";$("ocrImage").innerHTML="";const c=document.createElement("canvas");c.width=canvas.width;c.height=canvas.height;c.getContext("2d").drawImage(canvas,0,0);$("ocrImage").appendChild(c);await ocrLoad();const r=await Tesseract.recognize(c.toDataURL("image/png"),"eng",{logger:m=>m.progress&&($("ocrStatus").textContent=Math.round(m.progress*100)+"%")});$("ocrText").value=r.data.text;$("ocrStatus").textContent="Complete"};$("copyOcr").onclick=()=>navigator.clipboard?.writeText($("ocrText").value);$("saveOcr").onclick=()=>download(new TextEncoder().encode($("ocrText").value),"recognized-text.txt","text/plain");

$("quality").oninput=e=>$("qualityLabel").textContent=e.target.value+"%";$("maxDimension").oninput=e=>$("dimensionLabel").textContent=e.target.value+" px";
$("compressImageBtn").onclick=async()=>{const p=current();if(!p)return;const max=+$("maxDimension").value,target=+$("targetSize").value;let q=+$("quality").value/100,s=Math.min(1,max/Math.max(p.img.naturalWidth,p.img.naturalHeight)),c=document.createElement("canvas");c.width=Math.max(1,p.img.naturalWidth*s);c.height=Math.max(1,p.img.naturalHeight*s);const x=c.getContext("2d");x.filter=filter(p);x.drawImage(p.img,0,0,c.width,c.height);let b=await new Promise(r=>c.toBlob(r,"image/jpeg",q));if(target)for(let i=0;i<30&&b.size>target;i++){q=Math.max(.02,q*.8);b=await new Promise(r=>c.toBlob(r,"image/jpeg",q))}$("compressResult").textContent=`Result ${(b.size/1024).toFixed(1)} KB${target?(b.size<=target?" — target reached":" — target not reached"):""}`;download(await b.arrayBuffer(),"compressed.jpg","image/jpeg")};
$("compressPdfBtn").onclick=async()=>{if(!S.pages.length)return;const q=+$("quality").value/100,b=await pdfBytes(S.pages.map((_,i)=>i),q),target=+$("targetSize").value;$("compressResult").textContent=`PDF ${(b.length/1024).toFixed(1)} KB${target?(b.length<=target?" — target reached":" — target not reached"):""}`;download(b,"compressed.pdf","application/pdf")};

function openCamera(){navigator.mediaDevices?.getUserMedia({video:{facingMode:{ideal:S.facing},width:{ideal:1920}},audio:false}).then(stream=>{S.camera=stream;$("video").srcObject=stream;$("cameraModal").classList.remove("hidden")}).catch(()=>toast("Camera permission unavailable"))}
function closeCamera(){S.camera?.getTracks().forEach(t=>t.stop());S.camera=null;$("cameraModal").classList.add("hidden")}$("cameraBtn").onclick=openCamera;$("startScan").onclick=openCamera;$("closeCamera").onclick=closeCamera;$("flipCamera").onclick=()=>{S.facing=S.facing==="environment"?"user":"environment";closeCamera();openCamera()};$("capture").onclick=()=>{const v=$("video"),c=document.createElement("canvas");c.width=v.videoWidth;c.height=v.videoHeight;c.getContext("2d").drawImage(v,0,0);c.toBlob(async b=>{S.pages.push(await fileToImage(new File([b],"scan.jpg",{type:"image/jpeg"})));S.current=S.pages.length-1;closeCamera();refresh();toast("Page captured")},"image/jpeg",.94)};

$("fileInput").onchange=e=>{importFiles([...e.target.files]);e.target.value=""};$("heroInput").onchange=e=>{importFiles([...e.target.files]);e.target.value=""};$("addInput").onchange=e=>{importFiles([...e.target.files]);e.target.value=""};
$("dropZone").addEventListener("dragover",e=>{e.preventDefault();$("dropZone").classList.add("drag")});$("dropZone").addEventListener("dragleave",()=>$("dropZone").classList.remove("drag"));$("dropZone").addEventListener("drop",e=>{e.preventDefault();$("dropZone").classList.remove("drag");importFiles([...e.dataTransfer.files])});
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{if(!S.pages.length){toast("Import a document first");return}S.tool=b.dataset.tool;go("scan");$("cropNote").classList.toggle("hidden",S.tool!=="crop");render();buildToolbar()});
$("docTitle").onchange=()=>{$("status").textContent="Saved locally"};$("docTitle").onfocus=()=>{$("docTitle").select()};
$("zoomIn").onclick=()=>setZoom(S.zoom+.1);
$("zoomOut").onclick=()=>setZoom(S.zoom-.1);
$("fitPage").onclick=()=>fitZoom();
$("actualSize").onclick=()=>setZoom(1);
$("fullscreenPreview").onclick=()=>{const s=document.querySelector(".stage");if(!document.fullscreenElement)s.requestFullscreen?.();else document.exitFullscreen?.()};
$("pdfZoomIn").onclick=()=>updatePdfZoom(S.pdfZoom+.1);
$("pdfZoomOut").onclick=()=>updatePdfZoom(S.pdfZoom-.1);
$("pdfPrev").onclick=()=>{if(S.current>0){S.current--;refresh()}};
$("pdfNext").onclick=()=>{if(S.current<S.pages.length-1){S.current++;refresh()}};
$("pdfViewerBody").addEventListener("dblclick",()=>updatePdfZoom(S.pdfZoom>=1.8?.75:1.8));
window.addEventListener("resize",()=>{if(current())fitZoom()});
refresh();
})();